/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    AboutMe: typeof import('./src/components/AboutMe.vue')['default']
    AccountList: typeof import('./src/components/Financial/AccountList.vue')['default']
    Accounts: typeof import('./src/components/Financial/Accounts.vue')['default']
    BudgetAccounts: typeof import('./src/components/Financial/BudgetAccounts.vue')['default']
    Budgets: typeof import('./src/components/Financial/Budgets.vue')['default']
    EditBudget: typeof import('./src/components/Financial/EditBudget.vue')['default']
    ExcludedTransactions: typeof import('./src/components/Financial/ExcludedTransactions.vue')['default']
    Features: typeof import('./src/components/Features.vue')['default']
    HelloWorld: typeof import('./src/components/HelloWorld.vue')['default']
    LinkedAccounts: typeof import('./src/components/Financial/LinkedAccounts.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    SaveBudgetDialog: typeof import('./src/components/Financial/SaveBudgetDialog.vue')['default']
    SaveEstimateDialog: typeof import('./src/components/Financial/SaveEstimateDialog.vue')['default']
    TrackExpenses: typeof import('./src/components/Financial/TrackExpenses.vue')['default']
    Transactions: typeof import('./src/components/Financial/Transactions.vue')['default']
  }
}
